spring:
  application:
    name: BootProj-14MiniProjectWithProfiles
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: kanha123
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///nit_test_db
    username: root
