spring:
  application:
    name: BootProj-14MiniProjectWithProfiles
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: MYDB
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: MYDB
